modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="mekaneon"
version="${file.jarVersion}"
displayName="MekaNeon"
authors=""
description="Client-only neon outline for Mekanism induction cells/providers based on energy fill."

[[dependencies.mekaneon]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="CLIENT"

[[dependencies.mekaneon]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.mekaneon]]
modId="mekanism"
mandatory=true
versionRange="[1.21.1-10.7.17.83,)"
ordering="NONE"
side="CLIENT"
